language: node_js
node_js:
  - 8

script:
    - npm run build

# services:
#   - docker
  
# before_install:
#   - docker build -t kmpartner/ol-tutorial-webgl .
#   - docker run -d -p 127.0.0.1:80:80 kmpartner/ol-tutorial-webgl
#   - docker ps -a
  
