language: node_js
node_js:
- 8
script:
- npm run build
services:
- docker
after_success:
- docker build -t kmpartner/ol-tutorial-webgl .
- docker run -d -p 127.0.0.1:80:80 kmpartner/ol-tutorial-webgl
- docker ps -a
- echo "$DOCKER_USERNAME"
- echo "$TEST"
- docker login --username "$DOCKER_USERNAME" --password "DOCKER_PASSWORD"
- docker push kmpartner/ol-tutorial-webgl
env:
  global:
  - secure: DOCKER_USERNAME=ikcssrNYwtMkv8+lzNzmDLvOjaLX/6MKYzSYP03pfswHH+BNIq3NradnQSdoK9s4AMqEHrbQUmAkuFM9tYYGX7AxNwCQxiafI4S3+y4Woe+P3QDkxZ/D8D5t/KdceNH68N/kwF2BXxJJnX9EGbRv/SR5M5Movo/wLE69uPPs7Dr3E+8/QG8kskOCqk3VZBoP5ZutKvIpwBRHUk9bVFUF/NOOc+2NgY+bYVQGpxoXNKLp0JVN+UThvbW7EHyTvVJ0LGyHbqPfDcfMgRupUj8DcXSaP08VGGXW4rUT0DbvJZ2QHcwurMcnsmP4WlhVLWMNpr7+8R0W/YK8NbipUydpgzaMMTt3NJIbINIQdkCcZDx8QAUgy8VRqxRGQD9p/oKjPoHNaBG3K+eiGDB2ccItsD2s1LudhWxTNTJ6+3kH8DAnlVhUHBYI/f8xI3LVhjtRPQnlXNNXrfnZYkZKt9v/TubppM1GUYhHAsPwQyWhMRHgANQs4fb6xlWMAyC+Uu79MuO6CNnW4sHaIniiQN3PIZg1LZxi0ZB9JNV1POJ6iMb3CfPwKHT82dGkFaTqK35r9cG7XhBUuarZk9tF00o/KWUs3DkJXJADdYgr07otSAllZfhEAZzOZQcjghiBZEmdob+okSOiT1ypbMNFcyBTRpjMy59U+6WNN9bivBiMRbM=
  - secure: DOCKER_PASSWORD=EGuPKSTb9H0EqZr3OaXIOFgapaNLbpWr8Z+EDbaxLvlqO+Fc/WvSxbmRJH/PlWifj5VnirLKx/sR3rUMXJZFYB7+yB2NyhlnWQVeQ+g/9K8LkXaiNHjoRgoaGnu2EaDp2vJSInVQJPpg2Vkgo4Qt9yQ3XjdqZC5LbykLJopaFsNM8Ae+JfDn9cL+9nMDckKqupQ5Kiy3LtWyoxKfr/1APFjbyr74z2DRMZpoja450+ZdZtEpGw5xGjDcZBHnTc3nUON+Nv+foDL7PMXCLV5vZx2RcO6/SYHBgwOGOEDzig8jdCivIXaC8VaVcah2dsQVp04T3mzU3IXMm5vo4Kv8rOt9m2TvRzRi+8C1zpw9I9V3BirEUZ1vqw7vYp4nLD0F5Xx3zC8Fi8wWi4cjfLMumSMYy/rygsnlV2JkxYzCzLihmy18cUEsNGFQZvJEHxKEe/3o7ETgou9cebd04rUFRtL+ysh9Z14zREuJBzHa0RJoO6SvTblDTRKywRp3NBiBALbjrO4qeyobnnM2tDRYSDLHEDZKAgWllOhOiWgKC6/3EzBhW+rm6NQ+sojqFAN1D6VgkkhkgeQXCRtgWGbtP8pcyFFA1pr6gIG9GlnFhYCioJW7lF3P8FNME956e9vVOSCFxCTgLfM66lfcfcycv6Gii3HhHBMqudERdmSLfDU=
  - TEST=testenv2